# Generated by Django 3.1.4 on 2020-12-09 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('datum', models.DateField()),
                ('zeit', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Kunden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benutzername', models.CharField(max_length=16)),
                ('vorname', models.CharField(max_length=20)),
                ('nachname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('passwort', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='KundenEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.eventsentry')),
                ('kID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kunden')),
            ],
        ),
    ]
