# Generated by Django 3.1.4 on 2020-12-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201209_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsentry',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kunden',
            name='kunden_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
